// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProperties() {
  return window['go']['app']['CacheManagerApi']['GetProperties']();
}

export function GetTabletopSaves() {
  return window['go']['app']['CacheManagerApi']['GetTabletopSaves']();
}

export function WriteToPackData(arg1) {
  return window['go']['app']['CacheManagerApi']['WriteToPackData'](arg1);
}
