// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {properties} from '../models';

export function GetProperties():Promise<properties.ApplicationPropertiesView>;

export function GetTabletopSaves():Promise<void>;

export function WriteToPackData(arg1:string):Promise<Error|boolean>;
