// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTabletopSaves() {
  return window['go']['app']['CacheManagerApi']['GetTabletopSaves']();
}

export function PanicButton() {
  return window['go']['app']['CacheManagerApi']['PanicButton']();
}
