// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTabletopSaves():Promise<void>;

export function PanicButton():Promise<void>;
