// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {properties} from '../models';

export function ConstructPackCachedSave(arg1:string,arg2:string):Promise<void>;

export function CreateSingleplayerSave(arg1:string,arg2:string):Promise<void>;

export function Delete(arg1:string):Promise<void>;

export function GetProperties():Promise<properties.ApplicationPropertiesView>;

export function GetTabletopSaves():Promise<void>;

export function MergePackDataWithAnother(arg1:string,arg2:boolean):Promise<void>;

export function SetProperties(arg1:properties.ApplicationPropertiesView):Promise<void>;

export function WriteToPackData(arg1:string,arg2:string):Promise<void>;
