// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConstructPackedSave(arg1, arg2) {
  return window['go']['internal']['CacheManagerApi']['ConstructPackedSave'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['internal']['CacheManagerApi']['Delete'](arg1);
}

export function GetProperties() {
  return window['go']['internal']['CacheManagerApi']['GetProperties']();
}

export function GetTabletopSaves() {
  return window['go']['internal']['CacheManagerApi']['GetTabletopSaves']();
}

export function MergePackDataWithAnother(arg1, arg2) {
  return window['go']['internal']['CacheManagerApi']['MergePackDataWithAnother'](arg1, arg2);
}

export function WriteToPackData(arg1, arg2) {
  return window['go']['internal']['CacheManagerApi']['WriteToPackData'](arg1, arg2);
}
