// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConstructPackCachedSave(arg1, arg2) {
  return window['go']['internal']['CacheManagerApi']['ConstructPackCachedSave'](arg1, arg2);
}

export function CreateSingleplayerSave(arg1, arg2) {
  return window['go']['internal']['CacheManagerApi']['CreateSingleplayerSave'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['internal']['CacheManagerApi']['Delete'](arg1);
}

export function GetProperties() {
  return window['go']['internal']['CacheManagerApi']['GetProperties']();
}

export function GetTabletopSaves(arg1) {
  return window['go']['internal']['CacheManagerApi']['GetTabletopSaves'](arg1);
}

export function MergePackDataWithAnother(arg1, arg2) {
  return window['go']['internal']['CacheManagerApi']['MergePackDataWithAnother'](arg1, arg2);
}

export function OpenInExplorer(arg1) {
  return window['go']['internal']['CacheManagerApi']['OpenInExplorer'](arg1);
}

export function PanicButton() {
  return window['go']['internal']['CacheManagerApi']['PanicButton']();
}

export function Relocate(arg1, arg2) {
  return window['go']['internal']['CacheManagerApi']['Relocate'](arg1, arg2);
}

export function SetProperties(arg1) {
  return window['go']['internal']['CacheManagerApi']['SetProperties'](arg1);
}

export function WriteToPackData(arg1, arg2) {
  return window['go']['internal']['CacheManagerApi']['WriteToPackData'](arg1, arg2);
}
